# -*- coding: utf-8 -*-
"""Aula 05 - SENAI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d2ianfYC-6BtCRvDISlncpryjombOP3-

**AULA 05 - EXERCÍCIOS 🐱‍👤**
"""

#1
print('Exercício 1')
cidade = 'São Paulo'
adjetivo = 'sujo'
print('{} é {}.'.format(cidade, adjetivo))
print(' ')

#2
print('Exercício 2')
viagem = 'Brasília'
participante1 = 'Gabriel'
participante2 = 'Rafael'
print('{} e {} vão fazer uma viagem para {}.'.format(participante1, participante2, viagem))
print(' ')

#3
print('Exercício 3')
profissao = 'programador'
nome = input('Digite o seu nome: ')
print('{} quer ser {}.'.format(nome, profissao))

#Exercício 1
print('Digite um número e eu te direi o quadrado dele.')
number = int(input('Digite um número: '))
calc = number ** 2
print('O quadrado de {} é {}'.format(number, calc))

#Exercício 2
nome = input('Digite o seu nome: ')
sobrenome = input('Digite o seu sobrenome: ')
print('Olá {} {}. Seja bem vindo!'.format(nome, sobrenome))

#Exercício 3
num1 = input('Digite um número:')
num2 = input('Digite outro número: ')
print('A junção de {} e {} fica: {}{}'.format(num1, num2, num1, num2))

#Exercício 4
palavra = 'Python'
num = input('Digite um número: ')
print('{}{}'.format(palavra, num))

#Exercício 5
frase = 'Eu gosto de comer'
palavra0 = input('Digite uma coisa que você gosta de comer: ')
print('{} {}'.format(frase, palavra.lower()))

#DESAFIO
print('Bem vindo a Calculadora! ➕➖➗')
num1 = float(input('Digite um número: '))
num2 = float(input('Digite um número maior: '))
soma = num1 + num2
div = num2 / num1
multi = num1 * num2
sub = num2 - num1
divexat = num2 // num1
expo = num2 ** num1
print('Soma de {} + {} = {}'.format(num1, num2, soma))
print(' ')
print('Subtração de {} - {} = {}'.format(num2, num1, sub))
print(' ')
print('Multiplicação de {} x {} = {}'.format(num1, num2, multi))
print(' ')
print('Divisão de {} / {} = {}'.format(num2, num1, div))
print(' ')
print('Divisão exata de {} // {} = {}'.format(num2, num1, divexat))
print(' ')
print('Exponenciação de {} ^ {} = {}'.format(num2, num1, expo))