# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pd1m_3c-fEQSwybOCo4v0Gt2WFn4f4oX
"""

#DESAFIO NÚMERO 1

print('Bem vindo a Calculadora! ➕➖➗')
num1 = float(input('Digite um número: '))
num2 = float(input('Digite um número maior: '))
soma = num1 + num2
div = num2 / num1
multi = num1 * num2
sub = num2 - num1
divexat = num2 // num1
expo = num2 ** num1
print('Soma de {} + {} = {}'.format(num1, num2, soma))
print(' ')
print('Subtração de {} - {} = {}'.format(num2, num1, sub))
print(' ')
print('Multiplicação de {} x {} = {}'.format(num1, num2, multi))
print(' ')
print('Divisão de {} / {} = {}'.format(num2, num1, div))
print(' ')
print('Divisão exata de {} // {} = {}'.format(num2, num1, divexat))
print(' ')
print('Exponenciação de {} ^ {} = {}'.format(num2, num1, expo))